name: Wayclip Core Cargo

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-and-release:
    name: Publish Crate and Release Linux Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

      - name: Build Linux Binaries via Docker
        run: |
          docker build -t wayclip-builder .
          mkdir -p artifacts
          docker run --rm -v "${GITHUB_WORKSPACE}/artifacts":/out wayclip-builder

      - name: Package binaries for release
        shell: bash
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          tar -czvf "wayclip-${RELEASE_TAG}-x86_64-unknown-linux-gnu.tar.gz" -C artifacts .

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tar.gz"
