name: Wayclip CI & Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libglib2.0-dev

      - name: Publish Crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

      - name: Build Binaries in Docker
        run: |
          docker build -t wayclip-builder .
          mkdir -p artifacts
          docker run --rm -v "${GITHUB_WORKSPACE}/artifacts":/out wayclip-builder

      - name: Package Binaries for Release
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          tar -czvf "wayclip-${RELEASE_TAG}-x86_64-unknown-linux-gnu.tar.gz" -C artifacts .

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tar.gz"
