# .github/workflows/core.yml

name: Wayclip Core Cargo

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-and-release:
    name: Publish Crate and Release Linux Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            build-essential \
            libssl-dev \
            libwayland-dev \
            libpipewire-0.3-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            libavfilter-dev \
            libavdevice-dev \
            libswresample-dev \
            libasound2-dev \
            libdbus-1-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

      - name: Build binaries for Linux
        run: cargo build --release --bins --target x86_64-unknown-linux-gnu

      - name: Package binaries for release
        shell: bash
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}

          TARGET_DIR="target/x86_64-unknown-linux-gnu/release"
          ARTIFACT_DIR="wayclip-binaries"
          mkdir -p $ARTIFACT_DIR

          cp "$TARGET_DIR/daemon" "$ARTIFACT_DIR/"
          cp "$TARGET_DIR/trigger" "$ARTIFACT_DIR/"

          tar -czvf "wayclip-${RELEASE_TAG}-x86_64-unknown-linux-gnu.tar.gz" "$ARTIFACT_DIR"

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tar.gz"
